// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  UPSTASH_VECTOR_REST_TOKEN: string | undefined;
  UPSTASH_VECTOR_REST_URL: string | undefined;
}
