name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

env:
  UPSTASH_VECTOR_REST_URL: ${{ secrets.UPSTASH_VECTOR_REST_URL }}
  UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.UPSTASH_VECTOR_REST_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: test

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Lint
        run: bun run fmt

      # - name: Run tests
      #   run: bun run test

      - name: Run Build
        run: bun run build

  cloudflare-workers-local:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Install example
        run: bun add @upstash/vector@../..
        working-directory: examples/cloudflare-workers

      - name: Add environment
        run: |
          echo '[vars]' >> wrangler.toml
          echo "UPSTASH_VECTOR_REST_URL = \"$UPSTASH_VECTOR_REST_URL\"" >> ./wrangler.toml
          echo "UPSTASH_VECTOR_REST_TOKEN = \"$UPSTASH_VECTOR_REST_TOKEN\"" >> ./wrangler.toml
        working-directory: examples/cloudflare-workers

      - name: Start example
        run: bun dev &
        working-directory: examples/cloudflare-workers

      - name: Run tests
        run: bun test ci.test.ts
        working-directory: examples/cloudflare-workers
        env:
          DEPLOYMENT_URL: http://127.0.0.1:8787

  cloudflare-workers-deployed:
    concurrency: cloudflare-workers-deployed
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install example
        run: |
          bun add @upstash/vector@${{needs.release.outputs.version}}
          npm i -g wrangler
        working-directory: examples/cloudflare-workers

      - name: Add account ID
        run: echo 'account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"' >> wrangler.toml
        working-directory: examples/cloudflare-workers

      - name: Add environment
        run: |
          echo '[vars]' >> wrangler.toml
          echo "UPSTASH_VECTOR_REST_URL = \"$UPSTASH_VECTOR_REST_URL\"" >> ./wrangler.toml
          echo "UPSTASH_VECTOR_REST_TOKEN = \"$UPSTASH_VECTOR_REST_TOKEN\"" >> ./wrangler.toml
        working-directory: examples/cloudflare-workers

      - name: Deploy
        run: wrangler publish
        working-directory: examples/cloudflare-workers
        env:
          CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}

      - name: Test
        run: bun test examples/cloudflare-workers/ci.test.ts
        env:
          DEPLOYMENT_URL: https://upstash-vector.upsdev.workers.dev

  release:
    concurrency: release
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - cloudflare-workers-local
      # - nodejs-local
      # removed these two because they are skipped:
      # - nextjs-chat-to-website
      # - nextjs-server-actions
      # - nextjs-vercel-ai-sdk

    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo "::set-output name=version::v0.0.0-ci.${GITHUB_SHA}-$(date +%Y%m%d%H%M%S)"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Set version
        run: |
          echo $(jq --arg v "${{ steps.version.outputs.version }}" '(.version) = $v' package.json) > package.json
      - name: Install Dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Set NPM_TOKEN
        run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}

      - name: Publish ci version
        run: npm publish --tag=ci --verbose
        working-directory: ./dist

      - name: Sleep for 10s
        run: sleep 10s
        shell: bash
